Прототип прототипа гм
Kvantorium16/ToDo-List pull request #1
Opened 2023-05-20 10:41 UTC by Kirusha2281337

Надо сделать еще:
-Добавление итемов по кнопке
-Сортировка по активен не активен
-Сделать закругленные края у итемов и разграничить их между собой

2023-05-20 10:49 UTC, Kvantorium16 requested changes
Когда меняешь интерфейс, желательно прикладывать скриншот. Чтобы каждому участнику сразу было понятно, что получается, без необходимости качать твою версию проекта.

2023-05-20 10:49 UTC, Kvantorium16 commented on app/src/main/java/com/example/todo_list/MainActivity.kt
> +        plus.setOnClickListener{repeat++} //пытался сделать чтоб по кнопке добавлялось больше элементов ( не работает)
Не совсем понял, что ты хотел сделать.
Не нужно вносить нерабочий код. Либо исправь, либо убери.

2023-05-20 10:49 UTC, Kvantorium16 commented on app/src/main/res/layout/item_event.xml
> +        android:text="TextView" />
Замени захардкоженный текст чем-нибудь понятным. "Название заметки", например.

2023-05-20 16:09 UTC, Kirusha2281337 reviewed
Изменил то на что вы указали

2023-05-21 07:04 UTC, merged

2023-05-21 07:04 UTC, Kvantorium16 commented
Принято
![image](https://github.com/Kvantorium16/ToDo-List/assets/81939891/1585025c-30eb-4ece-9a9e-f26ec8cbc8e2)